var INIT_QUESTION_MAP = {};

INIT_QUESTION_MAP[QUESTION_TYPE_SINGLE] = {title: "单选题", custom_attr: {}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_MULTIPLE] = {title: "多选题", custom_attr: {}, question_type: QUESTION_TYPE_MULTIPLE, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_BLANK] = {title: "单行填空", custom_attr: {blank_type: "single"}, question_type: QUESTION_TYPE_BLANK, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {text_col:"20", text_row: "5"}}]};
INIT_QUESTION_MAP["multi_line_blank"] = {title: "多行填空", custom_attr: {blank_type: "multiple"}, question_type: QUESTION_TYPE_BLANK, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {text_col:"20", text_row: "5"}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_SCORE] = {title: "打分题", custom_attr: {min_answer_num: 1, max_answer_num: 5}, question_type: QUESTION_TYPE_SCORE, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP['nps_score'] = {title: "您向朋友或同事推荐我们的可能性有多大？", custom_attr: {min_answer_num: 0, max_answer_num: 10, disp_type: "nps_score"}, question_type: QUESTION_TYPE_SCORE, project_id: get_oid(project), option_list: [{title: " ", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_ORDER] = {title: "排序题", custom_attr: {}, question_type: QUESTION_TYPE_ORDER, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_MULTIPLE_BLANK] = {title: "多项填空题", custom_attr: {}, question_type: QUESTION_TYPE_MULTIPLE_BLANK, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {text_col:"15", text_row: "1"}}, {title: "选项2", is_open: false, custom_attr: {text_col:"15", text_row: "1"}}]};
INIT_QUESTION_MAP[DISP_TYPE_GEOGRAPHICAL] = {title: "您现在的位置在哪？", custom_attr: {disp_type: DISP_TYPE_GEOGRAPHICAL}, question_type: QUESTION_TYPE_MULTIPLE_BLANK, project_id: get_oid(project), option_list: [{title: "地址", is_open: false, custom_attr: {text_col:"15", text_row: "1", name_en: 'address'}}, {title: "经度", is_open: false, custom_attr: {text_col:"15", text_row: "1", name_en: 'longitude'}}, {title: "纬度", is_open: false, custom_attr: {text_col:"15", text_row: "1", name_en: 'latitude'}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_MATRIX_SINGLE] = {title: "矩阵单选题", custom_attr: {}, question_type: QUESTION_TYPE_MATRIX_SINGLE, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}], matrixrow_list: [{title: "矩阵行1", is_open: false, custom_attr: {}},{title: "矩阵行2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_MATRIX_MULTIPLE] = {title: "矩阵多选题", custom_attr: {}, question_type: QUESTION_TYPE_MATRIX_MULTIPLE, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}], matrixrow_list: [{title: "矩阵行1", is_open: false, custom_attr: {}},{title: "矩阵行2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_MATRIX_BLANK] = {title: "矩阵填空题", custom_attr: {}, question_type: QUESTION_TYPE_MATRIX_BLANK, project_id: get_oid(project), option_list: [{title: "请填空1", is_open: false, custom_attr: {text_col:"10", text_row: "1"}}, {title: "请填空2", is_open: false, custom_attr: {text_col:"10", text_row: "1"}}], matrixrow_list: [{title: "矩阵行1", is_open: false, custom_attr: {}},{title: "矩阵行2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_MATRIX_SCORE] = {title: "矩阵打分题", custom_attr: {min_answer_num: 1, max_answer_num: 5}, question_type: QUESTION_TYPE_MATRIX_SCORE, project_id: get_oid(project), option_list: [{title: "请打分1", is_open: false, custom_attr: {}}, {title: "请打分2", is_open: false, custom_attr: {}}], matrixrow_list: [{title: "矩阵行1", is_open: false, custom_attr: {}},{title: "矩阵行2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP[QUESTION_TYPE_DESC] = {title: "描述说明", custom_attr: {}, question_type: QUESTION_TYPE_DESC, project_id: get_oid(project)};
INIT_QUESTION_MAP['image_single'] = {option_list: [], title: "图片单选题", custom_attr: {disp_type: "image_single"}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project)};
INIT_QUESTION_MAP['image_multiple'] = {option_list: [], title: "图片多选题", custom_attr: {disp_type: "image_multiple"}, question_type: QUESTION_TYPE_MULTIPLE, project_id: get_oid(project)};
INIT_QUESTION_MAP['upload_file'] = {title: "上传题", custom_attr: {disp_type: "upload_file"}, question_type: QUESTION_TYPE_MULTIPLE_BLANK, project_id: get_oid(project), option_list: [{title: "选择文件上传", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP['split_line'] = {title: "分割线", custom_attr: {disp_type: "split_line"}, question_type: QUESTION_TYPE_DESC, project_id: get_oid(project)};
//vote question
INIT_QUESTION_MAP['font_vote_single'] = {title:"文字投票题", custom_attr: {disp_type: "singlevote", data_show: "on"},question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP['font_vote_multiple'] = {title:"文字投票题", custom_attr: {disp_type: "multiplevote", data_show: "on"},question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "选项1", is_open: false, custom_attr: {}}, {title: "选项2", is_open: false, custom_attr: {}}]};
INIT_QUESTION_MAP['image_vote_single'] = {title:"图片投票题", custom_attr: {disp_type: "imagevote_single", data_show: "on"}, option_list: [], question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project)};
INIT_QUESTION_MAP['image_vote_multiple'] = {title:"图片投票题", custom_attr: {disp_type: "imagevote_multiple", data_show: "on"}, option_list: [], question_type: QUESTION_TYPE_MULTIPLE, project_id: get_oid(project)};

//常用题目
INIT_QUESTION_MAP["sex"] = {title: "性别", custom_attr: {}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "男"}, {title: "女"}]};
INIT_QUESTION_MAP["city"] = {title: "您所在的城市是", question_type: QUESTION_TYPE_BLANK_DROPDOWN, custom_attr: {drop_type: "city"}, project_id: get_oid(project), option_list: [{title: "省份"},{title: "城市"},{title: "区/县"}]};
INIT_QUESTION_MAP["address"] = {title: "地址", question_type: QUESTION_TYPE_BLANK_DROPDOWN, custom_attr: {drop_type: "address"}, project_id: get_oid(project), option_list: [{title: "省份"},{title: "城市"},{title: "区/县"},{title: "街道"}]};
INIT_QUESTION_MAP["name"] = {title: "姓名", custom_attr: {}, question_type: QUESTION_TYPE_BLANK, project_id: get_oid(project), option_list: [{title: "A1", custom_attr:{text_row: "1", text_col: "10"}}]};
INIT_QUESTION_MAP["mobile"] = {title: "手机号码", custom_attr: {blank_type: "single", disp_type: "mobile"}, question_type: QUESTION_TYPE_BLANK, project_id: get_oid(project), option_list: [{title: "A1", custom_attr:{text_row: "1", text_col: "20", checkmethod: "mobile"}}]};
INIT_QUESTION_MAP["phone"] = {title: "电话", custom_attr: {blank_type: "single"}, question_type: QUESTION_TYPE_BLANK, project_id: get_oid(project), option_list: [{title: "A1", custom_attr:{text_row: "1", text_col: "20"}}]};
INIT_QUESTION_MAP["age"] = {title: "生日", custom_attr: {}, question_type: QUESTION_TYPE_BLANK_DROPDOWN, custom_attr: {drop_type: "age"}, project_id: get_oid(project), option_list: [{title: "年"},{title: "月"},{title: "日"}]};
INIT_QUESTION_MAP["date"] = {title: "请选择日期", question_type: QUESTION_TYPE_MULTIPLE_BLANK, custom_attr: {disp_type: "date"}, project_id: get_oid(project), option_list: [{title: "日期"}]};
INIT_QUESTION_MAP["time"] = {title: "请选择时间", question_type: QUESTION_TYPE_MULTIPLE_BLANK, custom_attr: {disp_type: "time"}, project_id: get_oid(project), option_list: [{title: "时"}, {title: "分"}]};
INIT_QUESTION_MAP["email"] = {title: "邮箱", custom_attr: {blank_type: "single"}, question_type: QUESTION_TYPE_BLANK, project_id: get_oid(project), option_list: [{title: "A1", custom_attr:{text_row: "1", text_col: "20", checkmethod: "email"}}]};
INIT_QUESTION_MAP["work_ex"] = {title: "工作年限", custom_attr: {}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "1年及以下"}, {title: "2-3年"}, {title: "4-5年"}, {title: "6-9年"}, {title: "10年及以上"}]};
INIT_QUESTION_MAP["education"] = {title: "受教育程度", custom_attr: {}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "初中及以下"}, {title: "高中"}, {title: "大专"}, {title: "本科"}, {title: "硕士及以上"}]};
INIT_QUESTION_MAP["income"] = {title: "个人月收入", custom_attr: {}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "2000元及以下"}, {title: "2001-3000元"}, {title: "3001-5000元"}, {title: "5001-8000元"}, {title: "8001-12000元"}, {title: "12001-20000元"}, {title: "20000元以上"}]};
INIT_QUESTION_MAP["company"] = {title: "工作单位性质", custom_attr: {}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "行政/事业单位"}, {title: "合资（包括外商独资）"}, {title: "国营（包括集体）"}, {title: "私营"}, {title: "境内上市股份公司"}, {title: "其他"}]};
INIT_QUESTION_MAP["marriage"] = {title: "婚姻状况", custom_attr: {}, question_type: QUESTION_TYPE_SINGLE, project_id: get_oid(project), option_list: [{title: "单身"}, {title: "已婚"}]};



var PAGE_TEMPLATE = '<li class="module paging" name="page"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><a class="DelPaging" href="javascript:;" style="display: none;"> <i class="del2-icon-active"></i></a></div></div><div class="topic_type_con"><div class="Drag_area" style="margin:0px;"><div class="icon_paging"></div><div class="fr con_paging">页码：<span></span></div></div></div></div></li>';
var QUESTION_ATTRIBUTE_TEMPLATE = '';

var INIT_TEMPLATE_MAP = {};
INIT_TEMPLATE_MAP[QUESTION_TYPE_SINGLE] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">单选题</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">选项1</label></li><li><input type="radio" name="radio" id="2" value="1"><label class="" for="">选项2</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_MULTIPLE] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">多选题</h4><ul class="unstyled"><li><input type="checkbox" name="radio" id="" value="1" /><label class="">选项1</label></li><li><input type="checkbox" name="radio" id="" value="2" /><label class="">选项2</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_BLANK] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">单行填空</h4><ul class="unstyled"><li><textarea name="" id="" cols="40" rows="1"></textarea></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["multi_line_blank"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">多行填空</h4><ul class="unstyled"><li><textarea name="" id="" cols="40" rows="5"></textarea></li></ul></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_BLANK_DROPDOWN] = '<li oid="${qmodel.qid}" issue="${question.question_type}" class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4>Q1</h4><a style="display: none;" title="题目设置" href="javascript:;" class="Bub"> <i class="setup-icon-active"></i></a><a style="display: none;" title="逻辑设置" href="javascript:;" class="Bub"> <i class="link-icon-active"></i></a><a style="display: none;" title="题目预览" href="javascript:;" class="Pre"><i class="zoom-icon-active"></i></a><a style="display: none;" title="题目复制" href="javascript:;" class="Bub"><i class="copy-icon-active"></i></a><a style="display: none;" title="题目删除" href="javascript:;" class="Del"><i class="del2-icon-active"></i></a></div></div><div class="topic_type_con"><div class="Drag_area"><div name="question" class="q_title th4 T_edit">$${question.title}</div></div><div class="selectTransverse">省份:<select id="${question.option_list[0]._id.$oid}" ><option value="">请选择</option></select>城市:<select id="${question.option_list[1]._id.$oid}"><option value="">请选择</option></select>地区:<select id="${question.option_list[2]._id.$oid}"><option value="">请选择</option></select></div></div></div><div style="display: none;" class="updown"><a href="javascript:;"><i class="up-icon-active" title="上移本题"></i></a><a href="javascript:;"><i class="down-icon-active" title="下移本题"></i></a></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_SCORE] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">打分题</h4><div class="grade"><table><tr><td align="right" class="">选项1</td><td><div class="grade_text" ><ul class="topic_ul"><li class="tc">1</li><li class="tc">2</li><li class="tc">3</li><li class="tc">4</li><li class="tc">5</li></ul></div></td></tr><tr><td align="right" class="">选项2</td><td><div class="grade_text" ><ul class="topic_ul"><li class="tc">1</li><li class="tc">2</li><li class="tc">3</li><li class="tc">4</li><li class="tc">5</li></ul></div></td></tr></table></div></div></div></li>';
INIT_TEMPLATE_MAP["nps_score"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">您向朋友或同事推荐我们的可能性有多大？</h4><div class="grade"><table style="width:500px;"><tr class="nps_tip_text"><td><span class="fl">不可能</span><span class="fr">极有可能</span></td></tr><tr><td><div class="grade_text nps_grade_text" ><ul class="topic_ul"><li class="tc">0</li><li class="tc">1</li><li class="tc">2</li><li class="tc">3</li><li class="tc">4</li><li class="tc">5</li><li class="tc">6</li><li class="tc">7</li><li class="tc">8</li><li class="tc">9</li><li class="tc">10</li></ul></div></td></tr></table></div></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_ORDER] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">排序题</h4><div class="pxul"><ul class="unstyled Sorting"><li class=""><label class="T_edit_min" name="option">选项1</label></li><li class=""><label class="T_edit_min" name="option">选项2</label></li></ul><div class="sort-right"><table class="table2"><tr><th class="w28">1</th><td>&nbsp;</td></tr><tr><th class="w28">2</th><td>&nbsp;</td></tr></table></div></div><div class="operationH"></div><p class="mt10">请将左面的项拖放到右面的框完成排序</p></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_MULTIPLE_BLANK] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">多项填空题</h4><div class="grade"><table width="290"><tr><td align="center" width="55"><div class="" >选项1</div></td><td align="left"><textarea name="" id="" cols="30" rows="1"></textarea></td></tr><tr><td align="center" width="55"><div class="" >选项2</div></td><td align="left"><textarea name="" id="" cols="30" rows="1" style="margin-top:5px;"></textarea></td></tr></table></div></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_MATRIX_SINGLE] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">矩阵单选题</h4><ul class="unstyled"><li><div class="matrix"><table class="table table-bordered td-Tc"><tr><td>&nbsp;</td><td class="">选项1</td><td class="">选项2</td></tr><tr><td class="">矩阵行1</td><td><input type="radio" name="radio" id="radio" value="radio" /></td><td><input type="radio" name="radio3" id="radio3" value="radio3" /></td></tr><tr><td class="">矩阵行2</td><td><input type="radio" name="radio2" id="radio2" value="radio2" /></td><td><input type="radio" name="radio4" id="radio4" value="radio4" /></td></tr></table></div></li></ul></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_MATRIX_MULTIPLE] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">矩阵多选题</h4><ul class="unstyled"><li><div class="matrix"><table class="table table-bordered td-Tc"><tr><td>&nbsp;</td><td class="">选项1</td><td class="">选项2</td></tr><tr><td class="">矩阵行1</td><td><input type="checkbox" name="checkbox"/></td><td><input type="checkbox" name="checkbox"/></td></tr><tr><td class="">矩阵行2</td><td><input type="checkbox" name="checkbox"/></td><td><input type="checkbox" name="checkbox"/></td></tr></table></div><div class="operationV"></div></li><li><div class="operationH"></div></li></ul></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_MATRIX_BLANK] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="Drag_area"><div class="th4 T_edit">矩阵填空题</div></div><ul class="unstyled"><li><div class="matrix"><table class="table table-bordered td-Tc"><tbody><tr><td>&nbsp;</td><td class="">请填空1</td><td class="">请填空2</td></tr><tr><td class="">矩阵行1</td><td><textarea name="" id="" cols="20" rows="1"></textarea></td><td><textarea name="" id="" cols="20" rows="1"></textarea></td></tr><tr><td class="">矩阵行2</td><td><textarea name="" id="" cols="20" rows="1"></textarea></td><td><textarea name="" id="" cols="20" rows="1"></textarea></td></tr></tbody></table></div></li><li></li></ul></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_MATRIX_SCORE] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="Drag_area"><div class="th4 T_edit">矩阵打分题</div></div><ul class="unstyled"><li><div class="matrix"><table class="table table-bordered  td-Tc"><tbody><tr><td>&nbsp;</td><td class="">请打分1</td><td class="">请打分2</td></tr><tr><td class="">矩阵行1</td><td><div class="dfW"><a href="javascript:;"> <i class="basic-too14-icon-active"></i></a><a href="javascript:;"> <i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a></div></td><td><div class="dfW"><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a></div></td></tr><tr><td class="">矩阵行2</td><td><div class="dfW"><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a></div></td><td><div class="dfW"><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a><a href="javascript:;"><i class="basic-too14-icon-active"></i></a></div></td></tr></tbody></table></div></li><li></li></ul></div></div></li>';
INIT_TEMPLATE_MAP[QUESTION_TYPE_DESC] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="Drag_area"><div class="th4 T_edit">描述说明</div></div></div></div></li>';
INIT_TEMPLATE_MAP["page"] = PAGE_TEMPLATE;
INIT_TEMPLATE_MAP["image_single"] = '<li class="module"><div class="topic_type"></div><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title">图片单选题</div></div><ul class="unstyled Imgli"><li class="dragZone"><div class="questionImgBox abor"><div class="AddQImgCon"><div class="uploader"><label><input type="file" name="files[]" multiple="multiple" title="Click to add Files"></label></div></div></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["image_multiple"] = '<li class="module"><div class="topic_type"></div><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title">图片多选题</div></div><ul class="unstyled Imgli"><li class="dragZone"><div class="questionImgBox abor"><div class="AddQImgCon"><div class="uploader"><label><input type="file" name="files[]" multiple="multiple" title="Click to add Files"></label></div></div></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["split_line"] = '<li class="module split_line"><div class="topic_type"><div class="topic_type_con"><div class="Drag_area dline"><div class="DividingLine"></div></div></div></div></li>';
INIT_TEMPLATE_MAP["upload_file"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"></div><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title"><p><span style="COLOR: #666666"><span style="FONT-SIZE: 16px"><span>上传题</span></span></span></p></div></div><div class="upFile"><div class="upBut"><div class="Hbuttom">选择文件</div></div><p><span>( 10MB以内 )</span></p><p style="color: #B1B1B1;margin-top: 45px;text-align: right;">*部分较老的手机可能不支持上传功能</p></div></div></div></li>';
//vote question
INIT_TEMPLATE_MAP["font_vote_single"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">文字投票题</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">选项1</label></li><li><input type="radio" name="radio" id="2" value="1"><label class="" for="">选项2</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["font_vote_multiple"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">文字投票题</h4><ul class="unstyled"><li><input type="checkbox" name="radio" id="" value="1" /><label class="">选项1</label></li><li><input type="checkbox" name="radio" id="" value="2" /><label class="">选项2</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["image_vote_single"] = '<li class="module"><div class="topic_type"></div><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title">图片投票题</div></div><ul class="unstyled Imgli"><li class="dragZone"><div class="questionImgBox abor"><div class="AddQImgCon"><div class="uploader"><label><input type="file" name="files[]" multiple="multiple" title="Click to add Files"></label></div></div></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["image_vote_multiple"] = '<li class="module"><div class="topic_type"></div><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title">图片投票题</div></div><ul class="unstyled Imgli"><li class="dragZone"><div class="questionImgBox abor"><div class="AddQImgCon"><div class="uploader"><label><input type="file" name="files[]" multiple="multiple" title="Click to add Files"></label></div></div></li></ul></div></div></li>';
//地理位置题
INIT_TEMPLATE_MAP[DISP_TYPE_GEOGRAPHICAL] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title">您现在的位置在哪？</div></div><a class="map_a" qid="${qmodel.qid}"><i></i>点击获取地理位置</a></div></div></li>';

//常用题目
INIT_TEMPLATE_MAP["sex"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">性别</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">男</label></li><li><input type="radio" name="radio" id="2" value="1"><label class="" for="">女</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["address"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div name="question" class="q_title th4 T_edit">地址</div><div class="selectTransverse"><select id="dy1" style="width:145px;"><option value="0">请选择省份</option></select><select id="dy2"><option value="0">请选择城市</option></select><select id="dy3"><option value="0">请选择区/县</option></select><br><textarea name="" id="" style="width:360px;height:45px;margin-top:10px;" placeholder="街道信息"></textarea></div></div></div></li>';
INIT_TEMPLATE_MAP["city"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div name="question" class="q_title th4 T_edit">您所在的城市是</div><div class="selectTransverse"><select id="dy1" style="width:145px"><option value="0">请选择省份</option></select><select id="dy2"><option value="0">请选择城市</option></select><select id="dy3"><option value="0">请选择区/县</option></select></div></div></div></li>';
INIT_TEMPLATE_MAP["name"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">姓名</h4><ul class="unstyled"><li><textarea cols="20" rows="1"></textarea></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["mobile"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">手机号码</h4><ul class="unstyled unstyled_mobile"><li><textarea cols="40" rows="1"></textarea></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["phone"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">电话</h4><ul class="unstyled"><li><textarea cols="40" rows="1"></textarea></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["age"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div name="question" class="q_title th4 T_edit">生日</div><div class="selectTransverse"><select id="dy1"><option value="0">请选择年</option></select><select id="dy2"><option value="0">请选择月</option></select><select id="dy3"><option value="0">请选择日</option></select></div></div></div></li>';
INIT_TEMPLATE_MAP["date"] = '<li class="module"><div class="topic_type"><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title">请选择日期</div></div><ul class="unstyled"><li><div id="5326a871a21ebe1a505892df" class="question_date_edit"><input  type="text" /><button class="Zebra_DatePicker_Icon Zebra_DatePicker_Icon_Inside" type="button" style="left: -30px; top: -3px;">Pick a date</button></div></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["time"] = '<li class="module" ><div class="topic_type"><div class="topic_type_con"><div class="Drag_area"><div name="question" class="th4 T_edit q_title">请选择时间</div></div><ul class="unstyled"><li><div class="Time_con"><select class="Time_Hour"><option value="-1">小时</option></select><span>:</span><select class="Time_Minute"><option value="-1">分钟</option></select></div></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["email"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><h4 class="th4 T_edit">邮箱</h4><ul class="unstyled"><li><textarea cols="40" rows="1"></textarea></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["work_ex"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">工作年限</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">1年及以下</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">2-3年</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">4-5年</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">6-9年</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">10年及以上</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["education"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">受教育程度</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">初中及以下</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">高中</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">大专</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">本科</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">硕士及以上</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["income"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">个人月收入</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">2000元及以下</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">2001-3000元</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">3001-5000元</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">5001-8000元</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">8001-12000元</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">12001-20000元</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">20000元以上</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["company"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">工作单位性质</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">行政/事业单位</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">合资（包括外商独资）</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">国营（包括集体）</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">私营</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">境内上市股份公司</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">其他</label></li></ul></div></div></li>';
INIT_TEMPLATE_MAP["marriage"] = '<li class="module"><div class="topic_type"><div class="topic_type_menu"><div class="setup-group"><h4></h4></div></div><div class="topic_type_con"><div class="th4">婚姻状况</div><ul class="unstyled"><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">单身</label></li><li><input type="radio" name="radio" id="1" value="1"><label class="" for="">已婚</label></li></ul></div></div></li>';
