var QUESTION_TYPE_SINGLE   = 2;
var QUESTION_TYPE_MULTIPLE = 3;
var QUESTION_TYPE_MATRIX_SINGLE = 4;
var QUESTION_TYPE_MATRIX_MULTIPLE = 5;
var QUESTION_TYPE_BLANK = 6;
var QUESTION_TYPE_MATRIX_SCORE = 7;
var QUESTION_TYPE_BLANK_DROPDOWN = 8;
var QUESTION_TYPE_SCORE = 50;
var QUESTION_TYPE_ORDER = 60;
var QUESTION_TYPE_DESC = 70;
var QUESTION_TYPE_MULTIPLE_BLANK = 95;
var QUESTION_TYPE_MATRIX_BLANK = 100;
var DISP_TYPE_GEOGRAPHICAL = 'geographical_multiple_blank';

var PROJECT_STATUS_CREATED = 0;
var PROJECT_STATUS_ACTIVATED = 1;
var PROJECT_STATUS_PAUSED = 3;
var PROJECT_STATUS_FINISHED = 2;
var PROJECT_STATUS_DELETED = -2;
var PROJECT_STATUS_DELETED_FOREVER = -1;

var CONDITION_RELATION_AND = 1;
var CONDITION_RELATION_OR = 2;

var CONDITION_OPERATION_TYPE_SELECTED = 1;
var CONDITION_OPERATION_TYPE_UNSELECTED = 2;
var CONDITION_OPERATION_TYPE_DISPLAYED = 3;
var CONDITION_OPERATION_TYPE_NOTDISPLAYED = 4;

var MOBILE_AUTH_QUESTION_STATUS_NORMAL = 1;
var MOBILE_AUTH_QUESTION_STATUS_NO_QUOTA = 2;
var MOBILE_AUTH_QUESTION_STATUS_NEED_GEETEST = 3;
